const DEFAULT_RECIPIENT = 'payments@youthnic.shop';
const MAX_ERROR_LENGTH = 500;

function emailConfig() {
  const recipient = (process.env.RATE_CARD_NOTIFICATION_TO || DEFAULT_RECIPIENT)
    .split(',')
    .map(value => value.trim())
    .filter(Boolean);
  return {
    recipient,
    apiKey: process.env.RESEND_API_KEY?.trim() || '',
    from: process.env.RESEND_FROM_EMAIL?.trim() || '',
  };
}

function escapeHtml(value) {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function printableValue(value) {
  if (value === null || value === undefined || value === '') return '—';
  if (typeof value === 'object') return JSON.stringify(value);
  return String(value);
}

function changedFields(previous, current) {
  if (previous && !current) {
    return Object.entries(previous)
      .filter(([key]) => !['id', 'updated_at', 'uploaded_at'].includes(key))
      .map(([field, before]) => ({ field, before, after: undefined }));
  }
  if (!previous || !current) return [];
  const ignore = new Set(['id', 'updated_at', 'uploaded_at']);
  const keys = new Set([...Object.keys(previous), ...Object.keys(current)]);
  return [...keys]
    .filter(key => !ignore.has(key) && printableValue(previous[key]) !== printableValue(current[key]))
    .map(key => ({ field: key, before: previous[key], after: current[key] }));
}

function eventLabel(action) {
  return {
    created: 'row added',
    updated: 'row updated',
    deleted: 'row deleted',
    period_saved: 'rate period saved',
    seeded: 'rate-card data reseeded',
    version_published: 'version published',
    version_rolled_back: 'version rolled back',
    test: 'delivery test',
  }[action] || 'rate card changed';
}

export function getRateCardNotificationConfig() {
  const config = emailConfig();
  const missing = [];
  if (!config.apiKey) missing.push('RESEND_API_KEY');
  if (!config.from) missing.push('RESEND_FROM_EMAIL');
  return {
    recipient: config.recipient.join(', '),
    configured: missing.length === 0,
    missing,
    deliveryMeaning: 'Accepted means the Resend API accepted the message. Inbox delivery/open confirmation requires a Resend webhook.',
  };
}

function messageFor(change) {
  const action = change.action || 'updated';
  const label = eventLabel(action);
  const marketplace = change.marketplace || 'flipkart';
  const sellerAccount = change.sellerAccount || 'default';
  const feeType = change.feeType ? ` · ${change.feeType.replace(/_/g, ' ')}` : '';
  const subject = `[Payments] ${marketplace}/${sellerAccount}${feeType}: ${label}`;
  const changes = changedFields(change.previousRow, change.row);
  const details = changes.length
    ? changes
    : Object.entries(change.row || {})
      .filter(([key]) => !['id', 'updated_at', 'uploaded_at'].includes(key))
      .map(([field, after]) => ({ field, before: undefined, after }));
  const summary = [
    `Action: ${label}`,
    `Marketplace: ${marketplace}`,
    `Seller account: ${sellerAccount}`,
    change.feeType ? `Fee type: ${change.feeType}` : null,
    change.actor?.email ? `Changed by: ${change.actor.email}` : null,
    Number.isFinite(change.insertedCount) ? `Rows added: ${change.insertedCount}` : null,
  ].filter(Boolean);
  const lines = [...summary, '', ...details.slice(0, 20).map(item =>
    item.before === undefined
      ? `${item.field}: ${printableValue(item.after)}`
      : `${item.field}: ${printableValue(item.before)} → ${printableValue(item.after)}`
  )];
  const htmlRows = details.slice(0, 20).map(item => `
    <tr>
      <td style="padding:6px 10px;border:1px solid #e2e8f0">${escapeHtml(item.field)}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0">${escapeHtml(item.before === undefined ? '—' : printableValue(item.before))}</td>
      <td style="padding:6px 10px;border:1px solid #e2e8f0">${escapeHtml(printableValue(item.after))}</td>
    </tr>`).join('');
  const html = `
    <div style="font-family:Arial,sans-serif;color:#1e293b;line-height:1.45">
      <h2 style="margin:0 0 12px">Rate card ${escapeHtml(label)}</h2>
      ${summary.map(line => `<p style="margin:4px 0">${escapeHtml(line)}</p>`).join('')}
      ${details.length ? `<table style="margin-top:16px;border-collapse:collapse;font-size:13px">
        <thead><tr><th style="padding:6px 10px;border:1px solid #e2e8f0;text-align:left">Field</th><th style="padding:6px 10px;border:1px solid #e2e8f0;text-align:left">Before</th><th style="padding:6px 10px;border:1px solid #e2e8f0;text-align:left">After</th></tr></thead>
        <tbody>${htmlRows}</tbody>
      </table>` : ''}
      <p style="margin-top:18px;color:#64748b;font-size:12px">This message was generated by the payment reconciliation application.</p>
    </div>`;
  return { subject, text: lines.join('\n'), html, changes };
}

async function writeLog(pool, values) {
  const result = await pool.query(
    `INSERT INTO rate_card_notification_log
      (event_type, recipient, subject, payload, status, provider_message_id, error_message, sent_at)
     VALUES ($1,$2,$3,$4::jsonb,$5,$6,$7,$8)
     RETURNING id, event_type, recipient, subject, status, provider_message_id, error_message, created_at, sent_at`,
    [
      values.eventType, values.recipient, values.subject, JSON.stringify(values.payload), values.status,
      values.providerMessageId || null, values.errorMessage || null, values.sentAt || null,
    ]
  );
  return result.rows[0];
}

export async function sendRateCardNotification(pool, change) {
  const config = emailConfig();
  const { subject, text, html, changes } = messageFor(change);
  const payload = {
    action: change.action || 'updated', marketplace: change.marketplace || 'flipkart',
    sellerAccount: change.sellerAccount || 'default', feeType: change.feeType || null,
    actor: change.actor?.email || null, rowId: change.row?.id || change.previousRow?.id || null,
    changes, insertedCount: change.insertedCount ?? null,
  };

  if (!config.apiKey || !config.from) {
    return writeLog(pool, {
      eventType: payload.action, recipient: config.recipient.join(', '), subject, payload,
      status: 'skipped', errorMessage: `Missing ${!config.apiKey ? 'RESEND_API_KEY' : 'RESEND_FROM_EMAIL'}`,
    });
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 10_000);
  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ from: config.from, to: config.recipient, subject, text, html }),
      signal: controller.signal,
    });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      const message = String(body?.message || body?.error || `Resend responded ${response.status}`).slice(0, MAX_ERROR_LENGTH);
      return writeLog(pool, { eventType: payload.action, recipient: config.recipient.join(', '), subject, payload, status: 'failed', errorMessage: message });
    }
    return writeLog(pool, {
      eventType: payload.action, recipient: config.recipient.join(', '), subject, payload,
      status: 'accepted', providerMessageId: body?.id || null, sentAt: new Date(),
    });
  } catch (error) {
    return writeLog(pool, {
      eventType: payload.action, recipient: config.recipient.join(', '), subject, payload,
      status: 'failed', errorMessage: String(error.message || error).slice(0, MAX_ERROR_LENGTH),
    });
  } finally {
    clearTimeout(timer);
  }
}

// Reused by payment reports that need the same audited Resend delivery path.
// Keeping this here means every finance email records the provider acceptance
// (or an actionable missing-config/error state) in one place.
export async function sendPaymentNotification(pool, { eventType, subject, text, html, payload = {} }) {
  const config = emailConfig();
  const recipient = config.recipient.join(', ');
  if (!config.apiKey || !config.from) {
    return writeLog(pool, {
      eventType, recipient, subject, payload,
      status: 'skipped', errorMessage: `Missing ${!config.apiKey ? 'RESEND_API_KEY' : 'RESEND_FROM_EMAIL'}`,
    });
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 10_000);
  try {
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: { Authorization: `Bearer ${config.apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ from: config.from, to: config.recipient, subject, text, html }),
      signal: controller.signal,
    });
    const body = await response.json().catch(() => ({}));
    if (!response.ok) {
      const errorMessage = String(body?.message || body?.error || `Resend responded ${response.status}`).slice(0, MAX_ERROR_LENGTH);
      return writeLog(pool, { eventType, recipient, subject, payload, status: 'failed', errorMessage });
    }
    return writeLog(pool, {
      eventType, recipient, subject, payload, status: 'accepted',
      providerMessageId: body?.id || null, sentAt: new Date(),
    });
  } catch (error) {
    return writeLog(pool, {
      eventType, recipient, subject, payload, status: 'failed',
      errorMessage: String(error.message || error).slice(0, MAX_ERROR_LENGTH),
    });
  } finally {
    clearTimeout(timer);
  }
}

export async function getRateCardNotificationStatus(pool) {
  const config = getRateCardNotificationConfig();
  const result = await pool.query(
    `SELECT id, event_type, recipient, subject, status, provider_message_id, error_message, created_at, sent_at
     FROM rate_card_notification_log ORDER BY created_at DESC LIMIT 20`
  );
  return { ...config, events: result.rows };
}

export async function sendRateCardNotificationTest(pool, actor) {
  return sendRateCardNotification(pool, {
    action: 'test', marketplace: 'system', sellerAccount: 'system', actor,
    row: { message: 'This is an administrator-requested Resend delivery test.' },
  });
}
