/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline": "#777587",
        "danger": "#E11D48",
        "tertiary-fixed": "#ffdbcc",
        "secondary": "#515f74",
        "secondary-fixed-dim": "#b9c7df",
        "canvas": "#F8FAFC",
        "secondary-container": "#d5e3fc",
        "primary-fixed": "#e2dfff",
        "teal": "#0F9F8C",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-tertiary-container": "#ffd2be",
        "on-primary-fixed-variant": "#3323cc",
        "on-background": "#1b1b24",
        "surface": "#FFFFFF",
        "on-secondary-container": "#57657a",
        "on-surface-variant": "#464555",
        "surface-container-highest": "#e4e1ee",
        "on-primary-fixed": "#0f0069",
        "inverse-surface": "#302f39",
        "background": "#fcf8ff",
        "on-tertiary-fixed": "#351000",
        "surface-bright": "#fcf8ff",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-low": "#f5f2ff",
        "primary-container": "#4f46e5",
        "primary": "#3525cd",
        "on-secondary": "#ffffff",
        "surface-dim": "#dcd8e5",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3effc",
        "inverse-primary": "#c3c0ff",
        "secondary-fixed": "#d5e3fc",
        "surface-container": "#f0ecf9",
        "border": "#E2E8F0",
        "surface-variant": "#e4e1ee",
        "surface-container-high": "#eae6f4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary-container": "#dad7ff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-tint": "#4d44e3",
        "error": "#ba1a1a",
        "tertiary-container": "#a44100",
        "success": "#059669",
        "ink": "#0F172A",
        "tertiary": "#7e3000",
        "warning": "#D97706",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-surface": "#1b1b24",
        "on-secondary-fixed": "#0d1c2e",
        "indigo-dark": "#3730A3"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "gutter": "24px",
        "xl": "32px",
        "base": "4px",
        "xs": "4px",
        "sidebar-width": "248px",
        "md": "16px",
        "lg": "24px",
        "card-padding": "20px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "financial-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "financial-md": ["Inter", "sans-serif"],
        "financial-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"]
      },
      fontSize: {
        "label-md": ["13px", { "lineHeight": "18px", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "financial-lg": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "financial-md": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "financial-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "500" }]
      }
    }
  },
  plugins: [],
}
