/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline": "#777587",
        "danger": "#E11D48",
        "tertiary-fixed": "#ffdbcc",
        "secondary": "#515f74",
        "secondary-fixed-dim": "#b9c7df",
        "canvas": "#F8FAFC",
        "secondary-container": "#d5e3fc",
        "primary-fixed": "#fbe9f0",
        "teal": "#0F9F8C",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c7c4d8",
        "on-tertiary-container": "#ffd2be",
        "on-primary-fixed-variant": "#902A4A",
        "on-background": "#1b1b24",
        "surface": "#FFFFFF",
        "on-secondary-container": "#57657a",
        "on-surface-variant": "#464555",
        "surface-container-highest": "#e4e1ee",
        "on-primary-fixed": "#902A4A",
        "inverse-surface": "#302f39",
        "background": "#F8FAFC",
        "on-tertiary-fixed": "#351000",
        "surface-bright": "#fcf8ff",
        "tertiary-fixed-dim": "#ffb695",
        "surface-container-low": "#F1F5F9",
        // ReconCentral brand — burgundy #902A4A. Previously this slot was
        // mapped to indigo #3525cd, which made every primary-coloured
        // element (Save buttons, chips, focus rings, sidebar accents)
        // fight the brand identity.
        "primary-container": "#fbe9f0",
        "primary": "#902A4A",
        "on-secondary": "#ffffff",
        "surface-dim": "#dcd8e5",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f3effc",
        "inverse-primary": "#f8b4c8",
        "secondary-fixed": "#d5e3fc",
        "surface-container": "#EEF2F7",
        "border": "#E2E8F0",
        "surface-variant": "#e4e1ee",
        "surface-container-high": "#eae6f4",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#3a485b",
        "on-tertiary-fixed-variant": "#7b2f00",
        "on-primary-container": "#902A4A",
        "primary-fixed-dim": "#f8b4c8",
        "surface-tint": "#902A4A",
        "error": "#ba1a1a",
        "tertiary-container": "#a44100",
        "success": "#059669",
        "ink": "#0F172A",
        "tertiary": "#7e3000",
        "warning": "#D97706",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-surface": "#1b1b24",
        "on-secondary-fixed": "#0d1c2e",
        "indigo-dark": "#5d1530"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.5rem",
        "2xl": "0.5rem",
        "full": "9999px"
      },
      letterSpacing: {
        tighter: "0",
        tight: "0",
        normal: "0",
        wide: "0",
        wider: "0",
        widest: "0",
      },
      spacing: {
        "sm": "8px",
        "gutter": "24px",
        "xl": "32px",
        "base": "4px",
        "xs": "4px",
        "sidebar-width": "248px",
        "md": "16px",
        "lg": "24px",
        "card-padding": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        "label-sm": ["11px", { "lineHeight": "16px", "letterSpacing": "0", "fontWeight": "500" }],
        "label-md": ["11px", { "lineHeight": "16px", "letterSpacing": "0", "fontWeight": "500" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "0", "fontWeight": "600" }],
        "financial-lg": ["28px", { "lineHeight": "36px", "letterSpacing": "0", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "financial-md": ["16px", { "lineHeight": "24px", "fontWeight": "500" }],
        "financial-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-md": ["18px", { "lineHeight": "26px", "letterSpacing": "0", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "0", "fontWeight": "600" }],
      }
    }
  },
  plugins: [],
}
